### ISSUE TITLE
Font viewer freezes

### ISSUE THREAD

**Issue by tgore323** [linuxmint/mint20-beta#138] opened 2020-06-20 02:40 UTC
Font Viewer (gnome-font-viewer) freezes when launched from Mint menu. It happens every time, and I must force quit or run killall to kill the process. 

System info: (https://termbin.com/xocf)

**Comment by xenopeek** [comment] 2020-06-20 05:52
Duplicate of #80

**Closed as completed by xenopeek** 2020-06-20 05:52 UTC
Labels: duplicate
