### ISSUE TITLE
Mate clock weather

### ISSUE THREAD

**Issue by Monsieurzik** [linuxmint/mint20-beta#51] opened 2020-06-15 14:07 UTC
After adding a location, no weather displayed on the clock. 

The same thing for the weather applet. 
![Capture du 2020-06-15 16-06-32](https://user-images.githubusercontent.com/29144843/84667179-4a636c00-af22-11ea-8797-f114053350f6.png)

**Comment by xenopeek** [comment] 2020-06-15 14:16
Duplicate of #49 

This is a known issue between the libmateweather library used by the MATE Clock applet and the weather information service, affecting more than just LM20: https://github.com/mate-desktop/libmateweather/issues/80. The latter is being migrated to new servers causing intermittent outages.

**Closed as completed by xenopeek** 2020-06-15 14:16 UTC
