### ISSUE TITLE
Cinnamon Workspace OSD doesn't go away

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#3] opened 2020-06-14 08:13 UTC
Workspace OSD doesn't go away after switching the workspace. It keeps staying on the screen until I reboot or log out.

Like this:

https://i.imgur.com/zLsrGfY.png

**Comment by pasch256** [comment] 2020-06-14 15:15
i confirmed that... cinammon beta in vm

**Comment by pasch256** [comment] 2020-06-14 15:30
workaround : go to the system setting, look for workspaces, and disable OSD. but i hope have a fix.

**Comment by xenopeek** [comment] 2020-06-14 15:45
Thanks for the workaround.

I can't managed to reproduce this on my end. Did you have the same issue while booted from the LiveISO? If you're not sure could you test to confirm? I can't reproduce it from the LiveISO or my install but to remove any variables might be useful to know whether you can reproduce it from the LiveISO.

**Comment by pasch256** [comment] 2020-06-14 15:57
i can check in a hour or so... and talk back.

**Comment by pasch256** [comment] 2020-06-14 16:29
ok, no problem with OSD when i use the usb stick for live session... so maybe the problem is the vm in my case... (maybe some keyboard stuff in vm manager, btw i use virtualbox)

**Comment by kelebek333** [comment] 2020-06-14 22:19
This issue fixed by this commit. https://github.com/linuxmint/cinnamon/commit/b0c2d459f68461d5f64c99fb8ca63c4ff2e36c6a

You can wait next version of Cinnamon 4.6.x.

**Closed as completed** 2020-06-15 02:21 UTC
