### ISSUE TITLE
Cannot move icons in Mate Menu

### ISSUE THREAD

**Issue by Skunkarific** [linuxmint/mint20-beta#41] opened 2020-06-15 01:22 UTC
I added the Opera browser from ,deb downloaded from www.opera.com, After rebooting, I tried to add the browser to the favorites menu by going to the "All programs" menu, then found the Opera icon, then clicked "Show in favorites".  It appeared in the menu, but I wanted to move it to the top row of the menu.  I tried dragging to the top of the menu, but it was unresponsive.  I tried moving other icons around, also unresponsive.

**Comment by xenopeek** [comment] 2020-06-15 05:19
Duplicate of #22

**Closed as completed by xenopeek** 2020-06-15 05:19 UTC
