### ISSUE TITLE
PolicyKit Elevation inconcistencies and translations in various dialogs

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#67] opened 2020-06-16 08:45 UTC
When a PolicyKit Elevation is required, a French user should see this dialog while "en tant qu'administrateur" is missing:
![Correcte_PK-Elevation](https://user-images.githubusercontent.com/66995112/84751770-3a4c9a80-afbd-11ea-8ac4-380a54b7e03f.png)

Instead, with linuxmint-drivers you see this:
![Gestionnaire_pilotes_wrong_PK](https://user-images.githubusercontent.com/66995112/84751899-65cf8500-afbd-11ea-8336-8f9031f11345.png)
User should see in English: "Authentication is required to run %Name of program" as Administrator"
or in French: "Une authentification est requise pour exécuter le %Nom du programme en tant qu'administrateur"

This is the same for org.cinnamon.settings-users:
![Users_Cinnamon_Wrong-PK](https://user-images.githubusercontent.com/66995112/84752343-eaba9e80-afbd-11ea-8ad5-103e5ea372b8.png)
and for mintsources:
![Sources-Logiciels-Wrong-PK](https://user-images.githubusercontent.com/66995112/84752413-04f47c80-afbe-11ea-82c3-3fd9122941cd.png)

An other inconsistencies in Timeshift PolicyKit Elevation:
![Bug-En-Trans_Timeshift_PK](https://user-images.githubusercontent.com/66995112/84752620-408f4680-afbe-11ea-93dc-326ba5c772c4.png)

User should see in French: "Une authentification est requise pour exécuter Timeshift en tant qu'administrateur" instead of English words.

An other inconsistencies in org.x.lightdm-settings:
![org x lightdm-settings](https://user-images.githubusercontent.com/66995112/84753283-138f6380-afbf-11ea-9778-38050b95b12a.png)
There is no bold text: "Authentication is required to run %Name of program" as Administrator".

**Comment by VaGNaroK** [comment] 2020-06-16 15:08
is the same problem for the Brazilian Portuguese language.

**Comment by clefebvre** [comment] 2020-06-16 15:17
Yes, this will be the same in all languages.

I don't think "as administrator" is needed. Using the program name as title is done by design, it's there to minimize the need for extra translations, or in the case of timeshift (which clearly shows the issue here), to work around missing translations.

I'd rather see Timeshift there than an English sentence which doesn't bring any additional info. Lightdm-settings needs a title, Users needs a provider. Timeshift needs a workaround or failing that a whole lot of translations it doesn't have.

**Comment by clefebvre** [comment] 2020-06-16 15:18
I'll have to check synaptic, it might work in French but only in a few languages.

**Comment by aureoud-fr85** [comment] 2020-06-16 20:41
Hi, @clefebvre,
I think you're right.
Instead, should we see a PolicyKit Gnome's version like this?
![Gnome_PolicyKit_Dialog](https://user-images.githubusercontent.com/66995112/84825929-7d8d2480-b022-11ea-85a5-2d1548a3d3c5.png)
https://blogs.gnome.org/mclasen/2018/12/04/a-policykit-refresher/

A bold title "Authentication required" translatable and a little text.
Regards,

**Comment by aureoud-fr85** [comment] 2020-06-17 09:47
Hi, @clefebvre there is another PolKit dialog when launching UFW-gui from system-preferences:
![PolKit_UFW](https://user-images.githubusercontent.com/66995112/84882773-08583880-b090-11ea-8ca5-579ae4d79b5d.png)
I think this should be the correct visual interface as it has sufficient and explicitly content.

Moreover, this is the PolicyKit dialog when you want to format USB key or dump ISO file on a USB key:
![PolKit_USB_Creator](https://user-images.githubusercontent.com/66995112/84892768-773c8e00-b09e-11ea-9a87-b9c4e9d71eaa.png)

The text in Bold is obvious referring to a python binaries and not the correct action but the dialog came from a correct translated sentence and from upstream component org.freedesktop.policykit.exec.

Regards,

**Comment by clefebvre** [comment] 2020-06-17 16:31
mintstick fixed

**Comment by clefebvre** [comment] 2020-06-17 16:39
lightdm-settings fixed

**Comment by clefebvre** [comment] 2020-06-17 16:45
cinnamon-settings-users fixed in git.

**Comment by clefebvre** [comment] 2020-06-17 16:53
timeshift fixed. We're all good.

**Closed as completed by clefebvre** 2020-06-17 16:53 UTC
Labels: reproduced, analyzed
