### ISSUE TITLE
Only One Monitor Detected in Live Mode

### ISSUE THREAD

**Issue by rockhazard** [linuxmint/mint20-beta#35] opened 2020-06-14 23:08 UTC
**Issue:** when starting up on a USB drive, Linux Mint 20 Cinnamon/Mate/Xfce do not recognize my second monitor.

**Note:** in order to successfully boot, I require either Compatibility Mode or nomodeset, as described in release notes. However,  the older Linux Mint 19.2 does not require these methods for me, and it doesn't recognize my second monitor either. Even so, on actual install, the second monitor is recognized in both 19.2 and 19.3. Therefore, I don't know whether this is by design, but older releases would see my second monitor in live mode. I have not tried to actually install LM20, as I only have my one production machine, so I don't know if this behaviour effects full installs.

**Frequency:** This problem occurs on boot from a USB media every time, whether I use Comparability Mode or nomodeset. Only bootup on the USB media is required to reproduce.

**System:** Asrock Taichi Ultimate mobo, i7 8700, 32gb ram, nvidia rtx 2060 graphics

**Comment by clefebvre** [comment] 2020-06-18 14:57
Can you take a screenshot of your display settings?

**Comment by clefebvre** [comment] 2020-06-22 10:00
Closing for lack info. We failed to identify the cause of the issue.

**Closed as completed by clefebvre** 2020-06-22 10:00 UTC
Labels: requested info
