### ISSUE TITLE
Brightness control does not work for OLED screens

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/mint20-beta#28] opened 2020-06-14 18:26 UTC
Having to [hack brightness support](https://github.com/Redsandro/thinkpad-x1-yoga/blob/master/roles/display/tasks/oled-brightness.yml) for laptops with an OLED screen was fair in 2018 (Mint 19) because it was new, but now it's time to support this out of the box.

Original issue posted here: https://github.com/linuxmint/cinnamon/issues/9365

---

```
 * Cinnamon version 4.6.3
 * Distribution - Mint 20 Beta
 * Intel no drivers
 * 64 bit
 ```

**Issue**

The brightness controls still do not work on Mint 20, although according to [this thread](https://www.reddit.com/r/thinkpad/comments/fmalfu/ubuntu_2004_brings_brightness_control_to_oled_x1/) they do work on Ubuntu 20.04

**Steps to reproduce**

Use Fn keys to adjust brightness

**Expected behaviour**

Brightness changes

**Other information**

The brightness OSD icon pops up but nothing changes

Thinkpad Yoga X1 OLED

**Comment by xenopeek** [comment] 2020-06-18 08:30
On the thread you link to there is also comment that it doesn't work for every system with Ubuntu 20.04 LTS. I think this will still depend on particular hardware configuration.

Would you test the same booting your system from the Ubuntu 20.04 LTS LiveISO?

**Comment by clefebvre** [comment] 2020-06-22 10:00
Closing for lack info. We failed to identify the cause of the issue.

**Closed as completed by clefebvre** 2020-06-22 10:00 UTC
Labels: requested info
