### ISSUE TITLE
Syntax problem in translations.

### ISSUE THREAD

**Issue by alan7000** [linuxmint/mint20-beta#26] opened 2020-06-14 16:28 UTC
Hello I noticed a problem with the text in the linux mint applications. There is marked at the end of all the sentences "[nbsp]". The problem is not very serious, but it's a stain.

![Capture d’écran du 2020-06-14 18-23-19](https://user-images.githubusercontent.com/7330585/84598679-c3a08780-ae6c-11ea-9730-d09411909853.png)

**Comment by InfoLibre** [comment] 2020-06-14 18:40
And a translation error on this page :
vérifier la présence -> vérifiez la présence

**Comment by alan7000** [comment] 2020-06-14 19:09
I just saw in launchpad the translations and I found the translation error. I don't know enough to correct this translation error.

**Comment by xenopeek** [comment] 2020-06-14 20:14
The Linux Mint Translation Guide includes a guide for translating on Launchpad, should this be useful to anybody: https://linuxmint-translation-guide.readthedocs.io/en/latest/translate.html

**Comment by clefebvre** [comment] 2020-06-14 23:11
I'll take care of it. I might add rules for us to automatically detect such cases as well.

**Comment by alan7000** [comment] 2020-06-15 09:39
Thank you. I think I can close the issue?

**Comment by clefebvre** [comment] 2020-06-16 10:08
Oh no, not yet :)

**Comment by NikoKrause** [comment] 2020-06-17 23:53
Duplicate of https://github.com/linuxmint/mint20-beta/issues/75?

**Comment by clefebvre** [comment] 2020-06-18 13:40
Yes and no, we still need to update translations for mintreport, but there's an item for this in trello so we can close this.

**Closed as completed by clefebvre** 2020-06-18 13:40 UTC
