### ISSUE TITLE
Keep option to change desktop layout to "Traditional" on the Welcome Screen

### ISSUE THREAD

**Issue by mendel5** [linuxmint/mint20-beta#147] opened 2020-06-20 10:49 UTC
Like many other people I prefer the traditional layout of the taskbar when using Linux Mint. After installing Linux Mint 20 Cinnamon Beta I was very sad to see that the option to switch between the traditional and modern taskbar layout is not included anymore in the Welcome Screen.

After searching the internet for a while I finally came across these posts:
* https://blog.linuxmint.com/?p=3915 and `STRG` + `F` for "traditional", e.g. https://blog.linuxmint.com/?p=3915#comment-155869
* https://forums.linuxmint.com/viewtopic.php?p=1831120
* https://github.com/linuxmint/mintwelcome/commit/d7f305d409bab0358cd8a5a34576a4ac44f08169

Then I installed all updates from the Update Manager and was glad to see that the option "Panel Layout" has been re-included in the "First Step" section of the Welcome Screen. After rebooting I was finally able to switch to the traditional layout.

When Linux Mint 20 Cinnamon Stable will be released please include the option to change the panel layout directly from the beginning without the necessity to install all updates first. Thanks!

For other people with the same issue, here are some tags/ keywords:
taskbar, task bar, panel, launch bar, quick launch bar, system tray, desktop layout, old, new, traditional, modern

**Comment by xenopeek** [comment] 2020-06-20 11:03
Duplicate of #38 

As per Trello board, this is fixed for final release.

**Closed as completed by xenopeek** 2020-06-20 11:03 UTC

**Comment by mendel5** [comment] 2020-06-20 11:06
Thanks for the quick feedback!
