### ISSUE TITLE
Mint Mate 20 - Screen distortion

### ISSUE THREAD

**Issue by Jildridge** [linuxmint/mint20-beta#12] opened 2020-06-14 08:53 UTC
On a laptop with integrated AMD GPU Radeon R2, I get a distorted screen (a display full of stair-like patterns) right after boot-up in life edition as well as after log-in in the installed edition. The only way to boot is using fail-safe mode. By now I located the problem at the window manager setting 'Marco+Compositing'. After switching to any other option, the system boots up without problems.

Although I guess this might be a general issue in ubuntu related distros,  will there be possibly a 'mint specific' fix?

Edit: Same on Mint xfce
That never happened in Version 19.x or earlier.

Edit2: What I have found more while searching the internet for that problem is, that this issue must have to do something with the special settings in the window managers for xfce (xfwm) and mate (marco). I am not very familiar with the command line settings of the managers; however I try to explain it in my amateurish words: The concerned compositor setting is called 'glx' vs. 'xpresent'. 
In xfce its possiple to change the setting via commandline from 'xpresent' (which is default) to 'glx'. Afterwards the compositing works fine. However for marco I haven't found any corresponding command.

**Comment by clefebvre** [comment] 2020-06-21 10:40
I think in Marco this is a build option, so users can't switch it at runtime. The only workaround would be to recompile marco without it.

I'll close this issue here because it's upstream from us and it's not something we'll be able to fix during the BETA.

I'd suggest the various kernels in 19.3 also, to see if 5.4 is responsible for this regression.

**Closed as completed by clefebvre** 2020-06-21 10:40 UTC
