### ISSUE TITLE
Screen tearing and blurry text on Intel graphics.

### ISSUE THREAD

**Issue by Jimbo-Jim** [linuxmint/mint20-beta#134] opened 2020-06-19 19:58 UTC
There is screen tearing on my monitor at any zoom level on 9900k Intel integrated graphics. I'm using an LG 4K 27 inch monitor with zoom set to 175%. Whether I have zoom set to 125% or 200% the amount of tearing seems identical and most of the tears are in the same place on my monitor. I don't get the same problem in 19.3 with HiDPI on. I'm between GPUs at the moment so I'll see how dedicated AMD graphics compare once my GPU arrives.

**Comment by gergo424** [comment] 2020-06-20 12:12
Same problem in issue https://github.com/linuxmint/mint20-beta/issues/55 with Intel 8th gen GPU

**Comment by xenopeek** [comment] 2020-06-20 17:58
Duplicate of #55 

See comment https://github.com/linuxmint/cinnamon-control-center/pull/238#issuecomment-646734935 for a test build of a fix/improvement for this issue.

**Closed as completed by xenopeek** 2020-06-20 17:58 UTC
Labels: duplicate
