### ISSUE TITLE
A common issue: bluetooth with wifi simultaneously

### ISSUE THREAD

**Issue by hammadimir** [linuxmint/mint20-beta#175] opened 2020-06-22 12:18 UTC
At first, I apologise. Currently, I am running Pop_OS 20.04. It is not possible for me to install mint right now. However, I found a common issue in mint 19.3, ubuntu 20.04, and pop os 20.04 of which I couldn't get a solution. Its an issue when I connect any bluetooth headphone, speaker etc simultaneously with wifi connected with my router. After using for 2 to 10mins, sometimes the wifi or the bluetooth headphone disconnects and again reconnects. It happens one or two times in an hour. Its common among the distros I have mentioned above. Although I haven't tested it in Mint 20 beta yet, I am confident enough of this issue to be recurred. Please have a look into this issue. I'll be happy if this problem goes away (if it is reproduced in this distro).

**Comment by clefebvre** [comment] 2020-06-22 12:34
I'd check in dmesg for clues coming from the hardware and drivers. I'll close the issue since it's not a BETA regression.

**Closed as completed by clefebvre** 2020-06-22 12:34 UTC
