### ISSUE TITLE
Codec don't install

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#11] opened 2020-06-14 08:47 UTC
I installed Linux Mint MATE 20 64-bit in VirtualBox, without any Ethernet interface. Then, after the installation and the first reboot, Linux Mint proposed me to install the French Language packages and the Multimedia codec packages. French Language packages were installed but the Multimedia codec packages were not, I had this error message :

![84587304-5108bb00-ae1e-11ea-8180-ad31a593feda](https://user-images.githubusercontent.com/3955499/84589059-700e4980-ae2c-11ea-823b-0490f6da7807.png)

**Comment by enigma131** [comment] 2020-06-14 09:11
same here.
and error in a repository: 
mint@mint:~$ sudo apt update
Ign:1 cdrom://Linux Mint 20 _Ulyana_ - Release amd64 20200610 focal InRelease
Err:2 cdrom://Linux Mint 20 _Ulyana_ - Release amd64 20200610 focal Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease                                              
Hit:5 http://archive.canonical.com/ubuntu focal InRelease                                           
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                      
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease              
Ign:8 http://packages.linuxmint.com ulyana InRelease
Hit:9 http://packages.linuxmint.com ulyana Release
Reading package lists... Done
E: The repository 'cdrom://Linux Mint 20 _Ulyana_ - Release amd64 20200610 focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by me2000** [comment] 2020-06-14 12:45
After installing Ulyana and doing an "apt update && apt upgrade && reboot" the installation through the GUI still fails with the error from the first post. I did not switch to a local mirror before doing this.

Doing a "apt install mint-meta-codecs" does work though without problems and systems reports are not showing the codecs as open problem anymore.

**Comment by enigma131** [comment] 2020-06-14 12:50
**apt install mint-meta-codecs**  is working too on live USB with partial upgrade. Problem is graphical interface.

**Comment by kbrenneman** [comment] 2020-06-14 14:20
It looks like installing `mint-meta-codecs` brings in `libavcodec-extra58`, which conflicts with `libavcodec58`. From the command line, it's happy to just remove libavcodec58, but the GUI might not.

**Comment by enigma131** [comment] 2020-06-14 15:36
oh yes, haven't see it before ...
apt update ...
apt install mint-meta-codecs
The following additional packages will be installed:
  cabextract ...
Suggested packages:
  frei0r-plugins .....
The following packages will be REMOVED:
  **libavcodec58**
The following NEW packages will be installed:
  cabextract ...
**libavcodec-extra58** ....
0 upgraded, 51 newly installed, 1 to remove and 176 not upgraded.
Need to get 17.0 MB of archives.
After this operation, 30.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

**Comment by clefebvre** [comment] 2020-06-14 23:13
Thanks, already on trello, it's a known bug.

**Closed as completed by clefebvre** 2020-06-14 23:13 UTC

**Comment by frozenMustelid** [comment] 2020-06-14 23:19
Confirmed on live DVD, language EN-US. Link to forum post (because blog post wasn't up yet and I didn't know that devs don't check the forums):
[https://forums.linuxmint.com/viewtopic.php?f=48&t=321910&p=1828242#p1828242](https://forums.linuxmint.com/viewtopic.php?f=48&t=321910&p=1828242#p1828242)
