### ISSUE TITLE
Instantly logged out

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mint20-beta#170] opened 2020-06-21 22:25 UTC
I'm sorry that this is not a bug that I have been able to reproduce, but I thought that I should report it anyway to make you aware that it is happening.

While testing the Mint 20 MATE Beta, I have been instantly logged out on 2 occasions so far:

. The first time I launched Graphical Disk Map (latest version of gdmap in the repos).

. When I double clicked on a scanned jpeg file on the desktop to view it.

In both cases, there was an almost instantaneous jump to the login screen and changes to open documents were lost. Carrying out said procedures a second time did not result in the same behaviour.

I have not experienced this with any other version of Mint.

**Comment by clefebvre** [comment] 2020-06-22 10:22
It looks like an Xorg crash. When this happens, go to console (Ctrl+Alt+F2) and check the logs (/var/log/Xorg.0.log, dmesg, ~/.xsession-errors). This is usually related to kernel or drivers.

I'll close this for now. If you find the cause and it's something on our side, please report it to github.com/linuxmint/linuxmint.

**Closed as completed by clefebvre** 2020-06-22 10:22 UTC
